### ISSUE TITLE
Karma Multi-layer EXR headers are different (Needs Legacy EXR Mode)

### ISSUE THREAD

**Issue by cjhosken** [cjhosken/NCCARenderFarmTools#12]

**Comment by cjhosken** [comment]
The viewer has been updated, there are a couple issues:

1. The border is a slightly darker grey unless the image goes behind it.
2. The image will stick out of the UI in the corners with border radius.
3. The infinite plane panning breaks when zooming out.

**Comment by cjhosken** [comment]
zooming / panning is fixed, black transparency has also been implemented. The grey borders is also looking better.

Still need to fix the ui sticking out.


I'm also re-considering an exr layer option (like in nuke), so people can view layers.

**Comment by cjhosken** [comment]
The image still sticks out of the UI.

I've got multi-layer viewing for non-exr images. EXR multi-layer viewing is still under development

**Comment by cjhosken** [comment]
basic EXR reading works, however the code isnt picking up multilayer exr channels.

**Comment by cjhosken** [comment]
With the decision to remove the standalone application, it's worth having another look at the exr viewer as it is done differently in the shelf tools.

**Comment by supersliser** [comment]
Created 3 versions (neither have been properly tested), one using my own logic, one using an external package and a third using anaconda ai's suggestion. Feel free to pick which you think is best @cjhosken

**Comment by cjhosken** [comment]
@supersliser Just had a look at the EXR split, am getting this error using a test render from Houdini (i'll attach the file for you to use)
```
['B', 'G', 'R']
['A']
# Traceback (most recent call last):
#   File "C:\Users\hoske\.ncca\ncca_shelftools\ncca_renderfarm\viewer\ncca_renderfarm_viewer.py", line 145, in open_item
#     dialog = QImageDialog(temp_file_path)  # Create QImageDialog instance
#   File "C:\Users\hoske\.ncca\ncca_shelftools\ncca_renderfarm\viewer\qimagedialog.py", line 39, in __init__
#     self.load_image(image_path, self.channels.currentText())  # Call the method to load and display the image
#   File "C:\Users\hoske\.ncca\ncca_shelftools\ncca_renderfarm\viewer\qimagedialog.py", line 50, in load_image
#     exr_to_png(image_path, alt_file_path)  # Convert EXR to PNG
#   File "C:\Users\hoske\.ncca\ncca_shelftools\utils.py", line 67, in exr_to_png
#     beauty_data = [np.reshape(d, (size[1], size[0])) for d in beauty_data]
#   File "C:\Users\hoske\.ncca\ncca_shelftools\utils.py", line 67, in <listcomp>
#     beauty_data = [np.reshape(d, (size[1], size[0])) for d in beauty_data]
#   File "<__array_function__ internals>", line 200, in reshape
#   File "C:\Users\hoske\AppData\Roaming\Python\Python310\site-packages\numpy\core\fromnumeric.py", line 298, in reshape
#     return _wrapfunc(a, 'reshape', newshape, order=order)
#   File "C:\Users\hoske\AppData\Roaming\Python\Python310\site-packages\numpy\core\fromnumeric.py", line 54, in _wrapfunc
#     return _wrapit(obj, method, *args, **kwds)
#   File "C:\Users\hoske\AppData\Roaming\Python\Python310\site-packages\numpy\core\fromnumeric.py", line 43, in _wrapit
#     result = getattr(asarray(obj), method)(*args, **kwds)
# ValueError: cannot reshape array of size 2764800 into shape (720,1280)
# #
```

[test.karmarendersettings.0001.zip](https://github.com/user-attachments/files/16479149/test.karmarendersettings.0001.zip)

**Comment by cjhosken** [comment]
The anaconda code doesn't properly work either, likely because the output file path is not consistent with what the code is expecting.

**Comment by cjhosken** [comment]
I've done a bunch of code changes and have got RGBA splitting working for the beauty passes. Still cant get the different LPE and AOV channels to be noticed. 

@supersliser I've deleted the other branches as they  didn't work. I'd prefer that you test your code yourself instead of guessing and then sending it over to me to check.

Theres an exr_channels.py alongside 2 exr images in the root of the code for you to play around with (it doesnt work at the moment, feel free to rewrite as much as you want)

sky.exr should only have one layer,
flip.exr should have multiple layers

**Comment by cjhosken** [comment]
Made some progress! Went back to using OpenEXR in python and image reading works for all arnold, blender, and general images.

It seems Houdini does things differently and thats causing alot of issues. I'll further look into that.

**Comment by cjhosken** [comment]
Works with Mantra, and works with Karma *IF* you "Enable Legacy EXR Mode" in the karmarendersettings/Husk/Rendering

**Comment by cjhosken** [comment]
Hope to soon fix this, but I'll leave it until I know more. 

Current solution for Karma: *Enable Legacy EXR Mode*
<img width="291" alt="image" src="https://github.com/user-attachments/assets/b2a829b3-30c0-4b3b-b28d-cd783e101997">
