### ISSUE TITLE
Crashes while render Houdini XPU

### ISSUE THREAD

**Issue by cjhosken** [cjhosken/NCCARenderFarmTools#15]
[13:13:07] Karma XPU delegate not supported on this machine
[13:13:07] Can't find Hydra plugin 'BRAY_HdKarmaXPU'. Choose one of:
[13:13:07]   - BRAY_HdKarma (Karma CPU)
[13:13:07]   - BRAY_HdKarmaXPU (Karma XPU) - unsupported
[13:13:07]   - HD_HoudiniRendererPlugin (Houdini GL) - unsupported
[13:13:07]   - HdStormRendererPlugin (GL) - unsupported
[13:13:07] Unable to load render plugin: BRAY_HdKarmaXPU
Traceback (most recent call last):
  File "/opt/software/hfs20.0.506/bin/hrender.py", line 241, in <module>
    render(args)
  File "/opt/software/hfs20.0.506/bin/hrender.py", line 226, in render
    rop_node.render(
  File "/opt/software/hfs20.0.506/houdini/python3.10libs/hou.py", line 78633, in render
    return _hou.RopNode_render(self, *args, **kwargs)
hou.OperationFailed: The attempted operation failed.
Error:       Command Exit Code: 1
             Failed to complete render: exit code 1
Use a Log Viewer with External Render Processes enabled for more information.
ERROR: non-zero child exit status: 1

Due to the fact theres no gpus in the renderfarm

**Comment by cjhosken** [comment]
https://github.com/cjhosken/NCCARenderFarmTools/issues/17
