### ISSUE TITLE
Qb needs to be updated (Qb import error)

### ISSUE THREAD

**Issue by cjhosken** [cjhosken/NCCARenderFarmTools#34]
Qb is throwing a nasty error when Maya or Houdini tries to import qb.

```
Traceback (most recent call last):
  File "\\bournemouth.ac.uk\data\student\home\FMC\s5605094\.ncca\ncca_shelftools\ncca_renderfarm\submit.py", line 116, in submit_project
    import qb
  File "C:\Program Files\pfx\qube\api\python\qb\__init__.py", line 29, in <module>
    exec('from . import '+qbPythonVer+' as _qb')
  File "<string>", line 1, in <module>
ImportError: cannot import name '_qb39' from partially initialized module 'qb' (most likely due to a circular import) (C:\Program Files\pfx\qube\api\python\qb\__init__.py)

cannot import name '_qb39' from partially initialized module 'qb' (most likely due to a circular import) (C:\Program Files\pfx\qube\api\python\qb\__init__.py)
```

**Comment by cjhosken** [comment]
This seems to happen on BOTH linux and windows. Is Qube outdated?

**Comment by cjhosken** [comment]
Problem is due to the fact that Maya and Houdini are running on Python 3.9, the current qb installation is only setup for python 3.8.

Seems like we'll need to update to a newer version of Qube.
